### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aiyush-G**
Added default language tool API endpoint so it will work as soon as the repository is cloned, added a comment for where the API key could be changed

### CODE REVIEW

**Comment by sereneinserenade** [comment]
Hey @Aiyush-G, thanks for the PR... This is what I read on https://dev.languagetool.org/public-http-api 

image


and I decided not to include this because users might be confused if it suddenly stops working when they block. let me know your views...

**Comment by Aiyush-G** [comment]
Ah, that makes sense! I think it is best to leave it how it is then. I might create an "issue" in the repo so that if people look for the link then they can find it easily?

**Comment by sereneinserenade** [comment]
If you like, you can just leave the link in the README.md, update your PR, but write a description comment to warn users...

**Review by Aiyush-G — COMMENTED** [review]
V1 - Added URL

**Review by Aiyush-G — COMMENTED** [review]
V2 - Further Updates with fair-use

**Pull request merged**
